---
title: Author Contribution Ckecklist Form for ``A Burden Shared is a Burden \text{Halved:} A Fairness Adjusted Approach to Classification"

output:
  pdf_document: default
  html_document: default
---
<!--HOW TO COMPLETE THIS FORM:-->


```{=html}
<!--
1. Checkboxes in this document appear as follows: 

- [ ] This is a checkbox 

To check a checkbox, replace [ ] by [x], as follows: 

- [x] This is a checked checkbox 

Note that older versions of RStudio (versions lower than 1.3) may not create a formatted checkbox but will leave the original characters, i.e., literally "[ ]" or "[x]". It's fine to submit a PDF in this form.
 
2. For text answers, simply type the relevant text in the areas indicated. A blank line starts a new paragraph. 
 
3. Comments (like these instructions) provide additional instructions throughout the form. There is no need to remove them; they will not appear in the compiled document. 

4. If you are comfortable with Markdown syntax, you may choose to include any Markdown-compliant formatting in the form. For example, you may wish to include R code chunks and compile this document in R Markdown.
-->
```

This form documents the artifacts associated with the article (i.e., the data and code supporting the computational findings) and describes how to reproduce the findings.

# Part 1: Data

-   [ ] This paper does not involve analysis of external data (i.e., no data are used or the only data are generated by the authors via simulation in their code).

```{=html}
<!--
If box above is checked and if no simulated/synthetic data files are provided by the authors, please skip directly to the Code section. Otherwise, continue.
-->
```
-   [x] I certify that the author(s) of the manuscript have legitimate access to and permission to use the data used in this manuscript.

<!-- If data are simulated using random number generation, please be sure to set the random number seed in the code you provide -->

## Abstract

```{=html}
<!--
Provide a short (< 100 words), high-level description of the data
-->
```
This work contains two data sets.

(1) **COMPAS recidivism data set:**

-   Originally collected for the ProPublica story "Machine Bias".
-   The features contained in this data set are criminal history, jail and prison time, demographics, and a COMPAS risk scores for defendants from Broward County.
-   Goal is to predict whether a given defendant will recidivate, given the current features at hand.\
-   The original data set can be downloaded from ProPublica's github. <https://github.com/propublica/compas-analysis/tree/master>

(2) **Adult census income data set:**

-   This data set was collected from the 1994 US Census.
-   Data set containing demographic information such as age, education, marital status, occupation, etc... for individuals in the US from 1994.
-   Goal is to predict whether a given person makes above (class 2) or below (class 1) 50K a year.
-   The original data set can be downloaded from the UCI machine learning repository. <https://archive.ics.uci.edu/dataset/2/adult>

## Availability

-   [x] Data **are** publicly available.
-   [ ] Data **cannot be made** publicly available.

If the data are publicly available, see the *Publicly available data* section. Otherwise, see the *Non-publicly available data* section, below.

### Publicly available data

-   [x] Data are available online at:

    -   The COMPAS recidivism data set can be downloaded at <https://github.com/propublica/compas-analysis/tree/master>.
    -   The Adult census income data set can be downloaded at <https://archive.ics.uci.edu/dataset/2/adult>.

-   [ ] Data are available as part of the paper's supplementary material.

-   [ ] Data are publicly available by request, following the process described here:

-   [ ] Data are or will be made available through some other mechanism, described here:

<!-- If data are available by request to the authors or some other data owner, please make sure to explain the process of requesting access to the data. -->

### Non-publicly available data

```{=html}
<!--
The Journal of the American Statistical Association requires authors to make data accompanying their papers available to the scientific community except in cases where: 1) public sharing of data would be impossible, 2) suitable synthetic data are provided which allow the main analyses to be replicated (recognizing that results may differ from the "real" data analyses), and 3) the scientific value of the results and methods outweigh the lack of reproducibility.

Please discuss the lack of publicly available data. For example:
-   why data sharing is not possible,
-   what synthetic data are provided, and 
-   why the value of the paper's scientific contribution outweighs the lack of reproducibility.
-->
```
## Description

### File format(s)

```{=html}
<!--
Check all that apply
-->
```
-   [x] CSV or other plain text.
-   [ ] Software-specific binary format (.Rda, Python pickle, etc.):
-   [ ] Standardized binary format (e.g., netCDF, HDF5, etc.):
-   [ ] Other (please specify):

### Data dictionary

```{=html}
<!--
A data dictionary provides information that allows users to understand the meaning, format, and use of the data.
-->
```
-   [ ] Provided by authors in the following file(s):

-   [ ] Data file(s) is(are) self-describing (e.g., netCDF files)

-   [x] Available at the following URL:

    -   COMPAS recidivism data dictionary: <https://github.com/propublica/compas-analysis/tree/master>
    -   Adult census income data dictionary: <https://archive.ics.uci.edu/dataset/2/adult>

### Additional Information (optional)

```{=html}
<!-- 
OPTIONAL: Provide any additional details that would be helpful in understanding the data. If relevant, please provide unique identifier/DOI/version information and/or license/terms of use.
-->
```
# Part 2: Code

## Abstract

```{=html}
<!--
Provide a short (< 100 words), high-level description of the code. If necessary, more details can be provided in files that accompany the code. If no code is provided, please state this and say why (e.g., if the paper contains no computational work).
-->
```
Each figure in the paper is accompanied by its own folder containing a function file and a main file. The function file must be executed before running the main file. The main file produces numerical results and generates an accompanying plot. The function file for every figure are nearly identical, with minor modifications implemented to expedite computation in more complex tasks. Although parallel processing is utilized in some files, it is optional; these files can be run without parallel processing by replacing **'mclapply'** with **'lapply'**.

An accompanying R package named **fasi** is available on CRAN, which can be used to implement our algorithm on new data sets. However, please note that this R package was not directly used in the studies presented in the main paper.

## Description

### Code format(s)

```{=html}
<!--
Check all that apply
-->
```
-   [x] Script files
    -   [x] R
    -   [ ] Python
    -   [ ] Matlab
    -   [ ] Other:
-   [x] Package
    -   [x] R
    -   [ ] Python
    -   [ ] MATLAB toolbox
    -   [ ] Other:
-   [ ] Reproducible report
    -   [ ] R Markdown
    -   [ ] Jupyter notebook
    -   [ ] Other:
-   [ ] Shell script
-   [ ] Other (please specify):

### Supporting software requirements

```{=html}
<!--
Please cite all software packages in the References Section in similar fashion to paper citations, citing packages that are foundational to the research outcome (including packages that implement methods to which you compare your methods). You may elect to not cite packages used for supporting purposes. For R packages, note that running `citation('name_of_package')` often shows how the package authors wish to be cited. 
-->
```
#### Version of primary software used

```{=html}
<!--
(e.g., R version 4.3.1)
-->
```
R version 4.3.1

#### Libraries and dependencies used by the code

```{=html}
<!--
Include version numbers (e.g., version numbers for any R or Python packages used)
-->
```
There are no packages that are foundational to the implementation of the FASI algorithm. However, since users can estimate confidence scores from any machine learning model, we demonstrated our algorithm using various algorithms. The ones used in our report are,

**ML algorithms for estimating confidence scores**

1.  **GAM** - from the **'mgcv'** package on CRAN, version *'1.9.1'*.

2.  **adaboost** - from the **'JOUSBoost'** package on CRAN, version *'2.1.0'*.

3.  **Logistic Regression** - from the **'MASS'** package on CRAN, version *'7.3.60'*.

4.  **Nonparametric Naive Bayes** - from the **'naivebayes'** package on CRAN, version *'1.0.0'*.

5.  **XGBoost** - from the **'xgboost'** package on CRAN, version *'1.7.5.1'*.

**Packages for general simulation workflow**

1.  **tidyverse** - version *'2.0.0',* available on CRAN.

2.  **ggplot2** - version *'3.4.4',* available on CRAN.

### Supporting system/hardware requirements (optional)

```{=html}
<!--
OPTIONAL: System/hardware requirements including operating system with version number, access to cluster, GPUs, etc.
-->
```
### Parallelization used

-   [ ] No parallel code used
-   [x] Multi-core parallelization on a single machine/node
    -   Number of cores used: 10
-   [ ] Multi-machine/multi-node parallelization
    -   Number of nodes and cores used:

### License

-   [x] MIT License (default)
-   [ ] BSD
-   [ ] GPL v3.0
-   [ ] Creative Commons
-   [ ] Other: (please specify)

### Additional information (optional)

```{=html}
<!--
OPTIONAL: By default, submitted code will be published on the JASA GitHub repository (http://github.com/JASA-ACS) as well as in the supplementary material. Authors are encouraged to also make their code available in a public code repository, such as on GitHub, GitLab, or BitBucket. If relevant, please provide unique identifier/DOI/version information (e.g., a Git commit ID, branch, release, or tag). If the code and workflow are provided together, this section may be omitted, with information provided in the "Location" section below.
-->
```
# Part 3: Reproducibility workflow

```{=html}
<!--
The materials provided should provide a straightforward way for reviewers and readers to reproduce analyses with as few steps as possible. 
-->
```
## Scope

The provided workflow reproduces:

-   [ ] Any numbers provided in text in the paper
-   [x] The computational method(s) presented in the paper (i.e., code is provided that implements the method(s))
-   [x] All tables and figures in the paper
-   [ ] Selected tables and figures in the paper, as explained and justified below:

## Workflow

### Location

The workflow is available:

```{=html}
<!--
Check all that apply, and in the case of a Git repository include unique identifier, such as specific commit ID, branch, release, or tag.
-->
```
-   [ ] As part of the paper's supplementary material.
-   [x] In this Git repository: <https://github.com/bradleyrava/fasi_experiments>
-   [ ] Other (please specify):

```{=html}
<!--
Indicate where the materials (generally including the code, unless in a separate location and indicated in the previous section) are available. We strongly encourage authors to place their materials (but not large datasets) in a Git repository hosted on a site such as GitHub, GitLab, or BitBucket. If the repository is private during the review process, please indicate the location where it will be available publicly upon publication, and also include the materials as a zip file (e.g., obtained directly from the Git hosting site) as supplementary materials.
-->
```
### Format(s)

```{=html}
<!--
Check all that apply
-->
```
-   [x] Single master code file
-   [ ] Wrapper (shell) script(s)
-   [ ] Self-contained R Markdown file, Jupyter notebook, or other literate programming approach
-   [ ] Text file (e.g., a readme-style file) that documents workflow
-   [ ] Makefile
-   [ ] Other (more detail in *Instructions* below)

### Instructions

```{=html}
<!--
Describe how to use the materials provided to reproduce analyses in the manuscript. Additional details can be provided in file(s) accompanying the reproducibility materials. If no workflow is provided, please state this and say why (e.g., if the paper contains no computational work).
-->
```
### Expected run-time

Approximate time needed to reproduce the analyses on a standard desktop machine:

-   [ ] \< 1 minute
-   [ ] 1-10 minutes
-   [ ] 10-60 minutes
-   [x] 1-8 hours
-   [ ] \> 8 hours
-   [ ] Not feasible to run on a desktop machine, as described here:

### Additional information (optional)

```{=html}
<!--
OPTIONAL: Additional documentation provided (e.g., R package vignettes, demos or other examples) that show how to use the provided code/software in other settings.
-->
```
# Notes (optional)

```{=html}
<!--
OPTIONAL: Any other relevant information not covered on this form. If reproducibility materials are not publicly available at the time of submission, please provide information here on how the reviewers can view the materials.
-->
```
